### ISSUE TITLE
optional message 'is'

### ISSUE THREAD

**Issue by kurt-o-sys** [mikera/cljunit#5]
When writing a failing test, cljunit generates an AssertionFailedError with message being a map with the expected and actual value. In the clojure 'is'-macro of clojure.test, one can provide an additional message. It would be nice to have this message added to the AssertionFailedError.

The use case I really would like to have this is: when using clojure.test.check (generative testing), the shrinker gives extremely valuable information about the reason why the assertion failed. Passing the map returned by 'tc/quick-check' as message to the is-form, would be, well... very welcome.

Can the message passed in the 'is'-macro be added to the AssertionFailedError-message, so returning a map like `{:expected ... :actual ... :message ...}`?

**Comment by mikera** [comment]
Assume this is closed by your patch?

**Comment by kurt-o-sys** [comment]
right! thx.
